version: "3.1"
services:
  back_topmax-app:
    build:
      context: ./back_topmax
      dockerfile: Dockerfile
    container_name: back_topmax_app_container
    # image: a7medabdo6/care_managment
    volumes:
      - ./back_topmax/src:/back_topmax_App/src:ro
    ports:
      - "7001:7001"
  react:
    build:
      context: ./front_topmax
      dockerfile: Dockerfile
    container_name: React_front_topmax_container
    volumes:
      - ./front_topmax/src:/React_front_topmax/src:ro
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: always

  # nginx:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.nginx
  #   # volumes:
  #   #     - ./Care_Frontend/build:/usr/share/nginx/html:ro
  #   ports:
  #     - 82:80
  #   restart: always
